### ISSUE TITLE
icinga

### ISSUE THREAD

**Issue by Binog** [qistoph/MMM-nagios#1]
Hey, is this compatible with icinga2 ? Can You provide a (relative) path to the right php-script to receive the values!?
Thx

**Comment by qistoph** [comment]
Hi @Binog,

As stated in the [README](https://github.com/qistoph/MMM-nagios/blob/master/README.md) this module reads the output of [php-nagios-json](https://github.com/lizell/php-nagios-json). Please have a look at that project to see how to set it up.

Does this help you solve it?
