### ISSUE TITLE
Parameters inconsistent, can't get it to work with auth

### ISSUE THREAD

**Issue by dsegel** [qistoph/MMM-nagios#2]
Config parameters are inconsistent between the config example and the list below (pass/password, user/username).

_Also, I can't get it to work with nagios authentication turned on. It looks like it's not even sending the user to apache._

**NEVERMIND on the second issue - I didn't have node_rest_client installed. It's working now.**

**Comment by qistoph** [comment]
Thanks for reporting the inconsistency. I have updated the README.

Nice to see you have reported your solution too, since that might help someone out in the future.
