### ISSUE TITLE
Host status instead of service status

### ISSUE THREAD

**Issue by rubenix** [qistoph/MMM-nagios#3]
Hello there, Have it working on my MM, great work! Any chance to display host status??

edit: would be nice to show summary on host status and if any down print wich one is it. sorry but english is not my first language (nor the 2nd..)

thanks so much!

**Comment by qistoph** [comment]
Think I've got it fixed. Check out this new branch:
https://github.com/qistoph/MMM-nagios/tree/hosts

Could you let me know if it works for you?

**Comment by rubenix** [comment]
Hey thanks so much for your time!!

Works nice for the hosts, but now getting 'Loading....' forever on the
services section....

[image: IMG_20200316_112021[1].jpg]



*------------------------------**Pau, República & Multimèdia,*

*Rubens*


Missatge de Chris van Marle <notifications@github.com> del dia dl., 16 de
març 2020 a les 8:42:

**Comment by qistoph** [comment]
Could you share your config here? Mine seems to work fine

**Comment by rubenix** [comment]
sorry mate, got it working!!!

Thanks so much!!! appreciated


*------------------------------**Pau, República & Multimèdia,*

*Rubens*



Missatge de Chris van Marle <notifications@github.com> del dia dl., 16 de
març 2020 a les 11:53:

**Comment by rubenix** [comment]
replied so fast....

its taking same info...same info for services & hosts
do I need to change this line?
http://myserver/nagios/cgi-bin/statusJson.php


 {
    module: 'nagios',
    position: 'top_right',
    header: 'Nagios - Services',
    config: {
      statusUrl: 'http://raspberry/nagios/cgi-bin/statusJson.php',
      username:'myuser',
      password: 'mypass',
      showDetails: true,
      showHosts: false
    }
  },

  {
    module: 'nagios',
    position: 'top_right',
    header: 'Nagios - Hosts',
    config: {
      statusUrl: 'http://myserver/nagios/cgi-bin/statusJson.php',
      username:'myuser',
      password: 'mypass',
      showDetails: true,
      showHosts: true
    }
  },




*------------------------------**Pau, República & Multimèdia,*

*Rubens*


Missatge de Chris van Marle <notifications@github.com> del dia dl., 16 de
març 2020 a les 11:53:
