### ISSUE TITLE
way to add some css

### ISSUE THREAD

**Issue by rubenix** [qistoph/MMM-nagios#4]
Sorry to post in here; in fact this is not an issue but a 'feature request'.
Would be nice to show results of  'ok, warning, critical & unknown' in  'green, yellow, red & orange' colors.
I do not know how to accomplish that but I guess could be a way of adding css to module, isn't it?
Is that difficult to achieve? If you can give some directions I would try but Im not a coder and do not know where to start...

Thanks

**Comment by qistoph** [comment]
I've updated the code to included CSS classes in the element of each number.

You can find an example in the README:
https://github.com/qistoph/MMM-nagios#coloring

Feel free to re-open the issue if you need more help;

**Comment by rubenix** [comment]
that was fast!!!
Thanks so much. Working the color css!!!
Thanks!
