### ISSUE TITLE
Not Understanding the URL I need.

### ISSUE THREAD

**Issue by dayman226** [qistoph/MMM-nagios#5]
Im working on the module and I get it to show but get Loading.... I assume it is because of the status URL. I am unsure of how to get that URL I think. I am using Nagios XI if that makes a diffrence.

**Comment by qistoph** [comment]
You'll need to install https://github.com/lizell/php-nagios-json first and use the URL that the php-nagios-json is available at.

For example, I've placed the script on my host in `/var/www/nagios_stats.php` and I use the url `https://myhost.domain/nagios_stats.php`.

I'm not sure if php-nagios-json will work with Nagios XI. Please let me know if you've solved it.
